// <auto-generated />
namespace RosenCDK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreateTables_SeedData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateTables_SeedData));
        
        string IMigrationMetadata.Id
        {
            get { return "201703161446172_CreateTables_SeedData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
